### PR TITLE
[to discuss] convert to ES6 const

### PR DESCRIPTION
**Pull request by akash1810**
Move towards ES6 syntax, using `const`s over `var`s.

The motivation behind this is online courses, blogs etc are becoming more ES6 first; its better to use `const`s here to avoid any confusion during self study.

Furthermore, all the browsers [support `const`s now](http://caniuse.com/#search=const).

### CODE REVIEW

**Comment by tsop14** [comment]
👍 Yay to moving towards es6. 

Is it worth adding a comment somewhere that we are using es6, with some helpful links? Knowing there are different versions of JS might help avoid confusion, especially if they've started learning on an older resource (e.g. Mozilla [JavaScript basics](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics)) with `var`s and suddenly they've all gone.

**Comment by susiecoleman** [comment]
Awesome thanks @akash1810  👍 🎉 

I'm hoping to get some work done on the quiz before the new term starts in September so we could add some links as well

**Comment by akash1810** [comment]
> Is it worth adding a comment somewhere that we are using es6, with some helpful links?

👍  I've updated [`handout.md`](https://github.com/guardian/education-centre-quiz/blob/aa-docs/handout.md) in https://github.com/guardian/education-centre-quiz/pull/13 initially, with the intention of updating the variables section.

**Comment by akash1810** [comment]
Closing as it's been a while w/no activity.

**Pull request closed without merging**
